Space travel hub
Bigizi/Space-Travel-Hub pull request #96
Opened 2023-03-15 17:21 UTC by Bigizi

**Space-Travel-Hub project**
Space travel hub is a single-page application that displays the rockets, dragons, missions, and profiles
in this project, you are able to make reservations for rocket or dragon
This project has different components and styling
We have the following components: dragon.js, rocket.js, navigation.js, mission.js, and profile.js and these files have the corresponding styles.
We also have tests for each component.

2023-03-15 18:40 UTC, PinkMoon25 requested changes
Hi @Bigizi @rivasbolinga @djo1975 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/zyjCXPXNo39i0CB467/giphy.gif"/>

## Highlights
Linter checks :heavy_check_mark: 
gitflow :heavy_check_mark: 
Code reviews :heavy_check_mark: 
Pair-programming :heavy_check_mark: 
React redux :heavy_check_mark: 
Missions section :heavy_check_mark: 
live data from SpaceX Api :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-15 18:40 UTC, PinkMoon25 commented on src/components/dragons/Dragon.js
> +
- [ ] Great job implementing the project requirements, however please notice that when I book a rocket or a dragon, and go to my profile it is there, but when I come back to the rocket or dragons page the reserved badge is gone it is also not present under my profile section, I have recorded a small video to make it clear :point_down: 

https://user-images.githubusercontent.com/97521557/225404090-e5c2290a-93a2-4ba7-931d-042903b9e1d0.mp4

Please try to fix this by adding a conditional check like you have done for the missions, in the video you will see the mission when joined is preserved when I visit the mission page or my profile section again.

2023-03-15 18:40 UTC, PinkMoon25 commented on src/App.js
> +  }, [dispatch]);
- [ ] Hi Team, As mentioned in the requirements :point_down: 
![image](https://user-images.githubusercontent.com/97521557/225405524-b2f68e36-413d-49ae-9170-2a9866fc2f1e.png)

Please make sure that you dispatch the actions only when needed, so fetch rockets when you initially render the page then fetch dragons on dragons page and missions on missions page, remove this useEffect and dispatch from here and only use it inside your components so whenever they render the useEffect will fetch the data, you should add a conditional check also so it does not fetches data on every re-render, you can[ use redux dev tools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) to keep track of the actions you are dispatching

2023-03-15 18:40 UTC, PinkMoon25 commented on src/redux/Dragons/dragonSlice.js
> +// export default dragonSlice.reducer;
- [ ] Please remove this commented code as it is mentioned in the best practices, we do not commit old pieces of code to the codebase

2023-03-15 18:40 UTC, PinkMoon25 commented on src/__tests__/dragon.test.js
> +    // Test case for bookDragons action creator
- [ ] [OPTIONAL] I think you are missing some test case here, and also try to test your reducers as they are pure functions, maybe you can test them for each of the components, as currently you are only testing render part.

2023-03-15 18:40 UTC, PinkMoon25 commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] Please fix your MIT link as currently it is broken and giving a 404 error

2023-03-16 09:29 UTC, Davidosky007 approved these changes
Hi @Bigizi @djo1975  @rivasbolinga , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* All tests passed 👍 
* Well written PR description 👍 
* Good looking readme file 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 09:30 UTC, merged